name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Generate docs
        run: pnpm run generate

      - name: Add .nojekyll
        run: echo > .output/public/.nojekyll

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/public
